import express from "express";
import multer from "multer";
import { body, validationResult } from "express-validator";

const app = express();

app.set("view engine", "ejs");
app.set("views", "views");

app.use(express.urlencoded({ extended: true }));

app.use("/", (req, res, next) => {
    console.log(`${req.url} fetched with method ${req.method}`);
    next();
});

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        return cb(null, "./uploads");
    },
    filename: (req, file, cb) => {
        return cb(null, Date.now() + file.originalname);
    }
});

const fileFilter = (req, file, cb) => {
    const allowedTypes = ["image/jpeg", "image/png", "image/jpg", "image/gif", "image/webp"];
    if (allowedTypes.includes(file.mimetype)) {
        return cb(null, true);
    } else {
        return cb(new Error("Invalid file type"), false);
    }
}

const upload = multer({
    storage: storage,
    fileFilter: fileFilter
});

app.use("/uploads", express.static("uploads"));

app.get("/", (req, res) => {
    res.render("form", { errors: [], formData: {} });
});

app.post(
    "/register",
    upload.fields([{ name: "profilePicture", maxCount: 1 }, { name: "otherPictures", maxCount: 5 }]),
    [
        body("name").trim()
            .notEmpty()
            .withMessage("Name is required")
            .isLength({ min: 3 })
            .withMessage("Name should be atleast 3 characters long"),

        body("email").trim()
            .notEmpty()
            .withMessage("Email is required")
            .isEmail()
            .withMessage("Invalid email format"),

        body("password").trim()
            .notEmpty()
            .withMessage("Password is required")
            .isLength({ min: 6 })
            .withMessage("Password should be atleast 6 characters long"),

        body("confirmPassword").trim()
            .notEmpty()
            .withMessage("Confirm Password is required")
            .custom((value, { req }) => {
                if (value !== req.body.password) {
                    throw new Error("Passwords do not match");
                }
                return true;
            }),

        body("gender").trim()
            .notEmpty()
            .withMessage("Gender is required"),

        body("hobbies").trim()
            .notEmpty()
            .withMessage("Hobbies are required")
    ],
    (req, res) => {
        const errors = validationResult(req);
        console.log(errors.array());
        if (!errors.isEmpty()) {
            res.render("form", { errors: errors.array(), formData: req.body });
        } else {
            res.render("preview", { formData: req.body, files: req.files });
        }
    }
);

app.use((err, req, res, next) => {

    if (err instanceof multer.MulterError) {

        let message = "";
        if (err.code === "LIMIT_UNEXPECTED_FILE") {

            if (err.field === "otherPictures") {
                message = "You can upload maximum 5 other pictures";
            }
            else if (err.field === "profilePicture") {
                message = "Only one profile picture is allowed";
            }
            else {
                message = "Unexpected file uploaded";
            }
        }
        else {
            message = err.message;
        }

        return res.render("form", {
            errors: [
                {
                    path: err.field || "otherPictures",
                    msg: message
                }
            ],
            formData: req.body
        });
    }

    // Error generated by fileFilter
    if (err) {
        return res.render("form", {
            errors: [
                {
                    path: err.field || "profilePicture",
                    msg: err.message
                }
            ],
            formData: req.body
        });
    }

    next();
});

app.listen(8000, () => {
    console.log("Server is running on port 8000");
});
